// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcioedwsnxomfjiqsitd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjaW9lZHdzbnhvbWZqaXFzaXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzUyODcsImV4cCI6MjA1OTExMTI4N30.g06KG_VX7e1mJQ5re78eLAFFu8b21bkDAsybT75aJ_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);